language: node_js

node_js:
  - "11.10.1"

services:
 - postgresql

addons:
 - postgresql: '9.5'

cache:
  directories:
    - node_modules

before_script:
 - psql -c 'create database tunda;' -U postgres
script:
 - yarn test